# Generated by Django 6.0 on 2025-12-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('platform', models.CharField(choices=[('ps4', 'PlayStation 4'), ('ps5', 'PlayStation 5'), ('xbox_one', 'Xbox One'), ('xbox_sx', 'Xbox Series X|S'), ('pc', 'PC')], max_length=20, verbose_name='Платформа')),
                ('condition', models.CharField(choices=[('new', 'Новая'), ('used', 'Б/у')], max_length=10, verbose_name='Состояние')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name_plural': 'Объявления о продаже игр',
                'ordering': ['-published'],
            },
        ),
    ]
