# Generated by Django 6.0 on 2025-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesales', '0003_gamead_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/', verbose_name='Обложка'),
        ),
    ]
